val = input('Digite algo: ')
print('O tipo primitivo deste valor é: {}'.format(type(val)))
print('Só tem espaços? {}'.format(val.isspace()))
print('É um número? {}'.format(val.isnumeric()))
print('Tem apenas caracteres alfabéticos? {}'.format(val.isalpha()))
print('Tem apenas caracteres alfanuméricos? {}'.format(val.isalnum()))
print('Está em maiúsculas? {}'.format(val.isupper()))
print('Está em minúsculas? {}'.format(val.islower()))
print('Está capitalizada? {}'.format(val.istitle()))