nome = input('Qual seu nome?')
dia = input('Qual a sua data de nascimento?')
mes = input('Qual seu mês de nascimento?')
ano = input('Qual seu ano de nascimento?')
print('Olá {}! Pelo que você digitou, sua data de nascimento é {} de {} de {}, certo?'.format(nome, dia, mes, ano))
